/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  TenantMembers: () => import('#controllers/tenant_members_controller'),
  Tenants: () => import('#controllers/tenants_controller'),
}
