import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('boms', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table.string('version').notNullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'item_id', 'version'])
      table.index(['tenant_id', 'is_active'])
    })

    this.schema.createTable('bom_lines', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('bom_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('boms')
        .onDelete('RESTRICT')
      table
        .integer('component_item_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table.decimal('quantity', 14, 4).notNullable()
      table.string('uom').notNullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'bom_id'])
      table.index(['tenant_id', 'component_item_id'])
    })

    this.schema.createTable('workstations', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table.string('code').notNullable()
      table.string('name').notNullable()
      table.string('type').notNullable()
      table.decimal('hourly_rate', 14, 4).notNullable().defaultTo(0)
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'code'])
      table.index(['tenant_id', 'type'])
      table.index(['tenant_id', 'is_active'])
    })

    this.schema.createTable('workers', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table.string('name').notNullable()
      table.string('document').nullable()
      table.string('status').notNullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'status'])
      table.unique(['tenant_id', 'document'])
    })

    this.schema.createTable('worker_roles', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table.string('name').notNullable()
      table.string('code').notNullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'code'])
      table.index(['tenant_id', 'is_active'])
    })

    this.schema.createTable('worker_role_assignments', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('worker_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('workers')
        .onDelete('RESTRICT')
      table
        .integer('worker_role_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('worker_roles')
        .onDelete('RESTRICT')
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'worker_id', 'worker_role_id'])
      table.index(['tenant_id', 'worker_role_id'])
    })

    this.schema.createTable('operation_types', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table.string('code').notNullable()
      table.string('name').notNullable()
      table.string('category').notNullable()
      table.string('default_uom').nullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'code'])
      table.index(['tenant_id', 'category'])
      table.index(['tenant_id', 'is_active'])
    })

    this.schema.createTable('routings', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table.string('name').notNullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'is_active'])
    })

    this.schema.createTable('routing_operations', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('routing_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('routings')
        .onDelete('RESTRICT')
      table
        .integer('operation_type_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('operation_types')
        .onDelete('RESTRICT')
      table
        .integer('workstation_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('workstations')
        .onDelete('RESTRICT')
      table.integer('sequence').notNullable()
      table.decimal('setup_time', 14, 4).notNullable().defaultTo(0)
      table.decimal('cycle_time', 14, 4).notNullable().defaultTo(0)
      table.string('input_uom').nullable()
      table.string('output_uom').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'routing_id', 'sequence'])
      table.index(['tenant_id', 'operation_type_id'])
      table.index(['tenant_id', 'workstation_id'])
    })

    this.schema.createTable('manufacturing_orders', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table
        .integer('routing_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('routings')
        .onDelete('RESTRICT')
      table.decimal('quantity', 14, 4).notNullable()
      table.string('status').notNullable()
      table.date('start_date').nullable()
      table.date('due_date').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'status'])
      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'due_date'])
    })

    this.schema.createTable('production_batches', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('manufacturing_order_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('manufacturing_orders')
        .onDelete('RESTRICT')
      table.string('code').notNullable()
      table.string('status').notNullable()
      table.timestamp('started_at').nullable()
      table.timestamp('finished_at').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'code'])
      table.index(['tenant_id', 'manufacturing_order_id'])
      table.index(['tenant_id', 'status'])
      table.index(['tenant_id', 'started_at'])
    })

    this.schema.createTable('production_batch_inputs', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('production_batch_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('production_batches')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table
        .integer('stock_lot_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('stock_lots')
        .onDelete('RESTRICT')
      table.decimal('planned_quantity', 14, 4).notNullable().defaultTo(0)
      table.decimal('consumed_quantity', 14, 4).notNullable().defaultTo(0)
      table.string('uom').notNullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'production_batch_id'])
      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'stock_lot_id'])
    })

    this.schema.createTable('production_batch_outputs', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('production_batch_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('production_batches')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table
        .integer('stock_lot_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('stock_lots')
        .onDelete('RESTRICT')
      table.decimal('quantity', 14, 4).notNullable()
      table.string('uom').notNullable()
      table.string('type').notNullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'production_batch_id'])
      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'stock_lot_id'])
      table.index(['tenant_id', 'type'])
    })

    this.schema.createTable('operation_entries', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('production_batch_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('production_batches')
        .onDelete('RESTRICT')
      table
        .integer('manufacturing_order_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('manufacturing_orders')
        .onDelete('RESTRICT')
      table
        .integer('operation_type_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('operation_types')
        .onDelete('RESTRICT')
      table
        .integer('workstation_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('workstations')
        .onDelete('RESTRICT')
      table
        .integer('worker_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('workers')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table.decimal('input_quantity', 14, 4).nullable()
      table.decimal('output_quantity', 14, 4).nullable()
      table.string('uom').nullable()
      table.timestamp('started_at').nullable()
      table.timestamp('finished_at').nullable()
      table.integer('duration_minutes').nullable()
      table.string('status').notNullable()
      table.text('notes').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'production_batch_id'])
      table.index(['tenant_id', 'manufacturing_order_id'])
      table.index(['tenant_id', 'operation_type_id'])
      table.index(['tenant_id', 'workstation_id'])
      table.index(['tenant_id', 'worker_id'])
      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'started_at'])
    })
  }

  async down() {
    this.schema.dropTable('operation_entries')
    this.schema.dropTable('production_batch_outputs')
    this.schema.dropTable('production_batch_inputs')
    this.schema.dropTable('production_batches')
    this.schema.dropTable('manufacturing_orders')
    this.schema.dropTable('routing_operations')
    this.schema.dropTable('routings')
    this.schema.dropTable('operation_types')
    this.schema.dropTable('worker_role_assignments')
    this.schema.dropTable('worker_roles')
    this.schema.dropTable('workers')
    this.schema.dropTable('workstations')
    this.schema.dropTable('bom_lines')
    this.schema.dropTable('boms')
  }
}
