import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('piece_rate_rules', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('worker_role_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('worker_roles')
        .onDelete('RESTRICT')
      table
        .integer('operation_type_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('operation_types')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table
        .integer('workstation_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('workstations')
        .onDelete('RESTRICT')
      table.string('uom').notNullable()
      table.decimal('rate', 14, 4).notNullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('starts_at').nullable()
      table.timestamp('ends_at').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'worker_role_id'])
      table.index(['tenant_id', 'operation_type_id'])
      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'workstation_id'])
      table.index(['tenant_id', 'is_active'])
    })

    this.schema.createTable('worker_production_entries', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('worker_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('workers')
        .onDelete('RESTRICT')
      table
        .integer('worker_role_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('worker_roles')
        .onDelete('RESTRICT')
      table
        .integer('operation_entry_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('operation_entries')
        .onDelete('RESTRICT')
      table
        .integer('operation_type_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('operation_types')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table
        .integer('workstation_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('workstations')
        .onDelete('RESTRICT')
      table.decimal('quantity', 14, 4).notNullable()
      table.string('uom').notNullable()
      table.decimal('rate', 14, 4).notNullable()
      table.decimal('amount', 14, 2).notNullable()
      table.string('status').notNullable()
      table.timestamp('occurred_at').notNullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'worker_id'])
      table.index(['tenant_id', 'worker_role_id'])
      table.index(['tenant_id', 'operation_entry_id'])
      table.index(['tenant_id', 'operation_type_id'])
      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'occurred_at'])
      table.index(['tenant_id', 'status'])
    })

    this.schema.createTable('packaging_units', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table.string('code').notNullable()
      table.string('name').notNullable()
      table.decimal('unit_quantity', 14, 4).nullable()
      table.string('uom').nullable()
      table.boolean('is_active').notNullable().defaultTo(true)
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['tenant_id', 'code'])
      table.index(['tenant_id', 'is_active'])
    })

    this.schema.createTable('packing_entries', (table) => {
      table.increments('id')
      table
        .integer('tenant_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('tenants')
        .onDelete('RESTRICT')
      table
        .integer('production_batch_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('production_batches')
        .onDelete('RESTRICT')
      table
        .integer('item_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('items')
        .onDelete('RESTRICT')
      table
        .integer('stock_lot_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('stock_lots')
        .onDelete('RESTRICT')
      table
        .integer('packaging_unit_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('packaging_units')
        .onDelete('RESTRICT')
      table
        .integer('location_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('locations')
        .onDelete('RESTRICT')
      table.decimal('quantity', 14, 4).notNullable()
      table.decimal('package_count', 14, 4).notNullable()
      table.string('status').notNullable()
      table.timestamp('packed_at').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['tenant_id', 'production_batch_id'])
      table.index(['tenant_id', 'item_id'])
      table.index(['tenant_id', 'stock_lot_id'])
      table.index(['tenant_id', 'packaging_unit_id'])
      table.index(['tenant_id', 'location_id'])
      table.index(['tenant_id', 'packed_at'])
    })
  }

  async down() {
    this.schema.dropTable('packing_entries')
    this.schema.dropTable('packaging_units')
    this.schema.dropTable('worker_production_entries')
    this.schema.dropTable('piece_rate_rules')
  }
}
