/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BomLineSchema extends BaseModel {
  static $columns = ['bomId', 'componentItemId', 'createdAt', 'id', 'quantity', 'tenantId', 'uom', 'updatedAt'] as const
  $columns = BomLineSchema.$columns
  @column()
  declare bomId: number
  @column()
  declare componentItemId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare quantity: string
  @column()
  declare tenantId: number
  @column()
  declare uom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BomSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'itemId', 'tenantId', 'updatedAt', 'version'] as const
  $columns = BomSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare itemId: number
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string
}

export class CustomerSchema extends BaseModel {
  static $columns = ['createdAt', 'document', 'email', 'id', 'name', 'phone', 'status', 'tenantId', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InventoryBalanceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'locationId', 'quantityOnHand', 'quantityReserved', 'tenantId', 'updatedAt'] as const
  $columns = InventoryBalanceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare locationId: number
  @column()
  declare quantityOnHand: string
  @column()
  declare quantityReserved: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InventoryMovementSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'locationId', 'occurredAt', 'quantity', 'referenceId', 'referenceType', 'stockLotId', 'tenantId', 'type', 'unitCost', 'updatedAt'] as const
  $columns = InventoryMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare locationId: number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare quantity: string
  @column()
  declare referenceId: number | null
  @column()
  declare referenceType: string | null
  @column()
  declare stockLotId: number | null
  @column()
  declare tenantId: number
  @column()
  declare type: string
  @column()
  declare unitCost: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'isManufacturable', 'isPurchasable', 'isSellable', 'name', 'reorderPoint', 'sku', 'standardCost', 'tenantId', 'type', 'uom', 'updatedAt'] as const
  $columns = ItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isManufacturable: boolean
  @column()
  declare isPurchasable: boolean
  @column()
  declare isSellable: boolean
  @column()
  declare name: string
  @column()
  declare reorderPoint: string
  @column()
  declare sku: string
  @column()
  declare standardCost: string
  @column()
  declare tenantId: number
  @column()
  declare type: string
  @column()
  declare uom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LocationSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'isActive', 'name', 'tenantId', 'type', 'updatedAt'] as const
  $columns = LocationSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare tenantId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ManufacturingOrderSchema extends BaseModel {
  static $columns = ['createdAt', 'dueDate', 'id', 'itemId', 'quantity', 'routingId', 'startDate', 'status', 'tenantId', 'updatedAt'] as const
  $columns = ManufacturingOrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dueDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare quantity: string
  @column()
  declare routingId: number | null
  @column.date()
  declare startDate: DateTime | null
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OperationEntrySchema extends BaseModel {
  static $columns = ['createdAt', 'durationMinutes', 'finishedAt', 'id', 'inputQuantity', 'itemId', 'manufacturingOrderId', 'notes', 'operationTypeId', 'outputQuantity', 'productionBatchId', 'startedAt', 'status', 'tenantId', 'uom', 'updatedAt', 'workerId', 'workstationId'] as const
  $columns = OperationEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMinutes: number | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inputQuantity: string | null
  @column()
  declare itemId: number | null
  @column()
  declare manufacturingOrderId: number | null
  @column()
  declare notes: string | null
  @column()
  declare operationTypeId: number
  @column()
  declare outputQuantity: string | null
  @column()
  declare productionBatchId: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column()
  declare uom: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workerId: number | null
  @column()
  declare workstationId: number | null
}

export class OperationTypeSchema extends BaseModel {
  static $columns = ['category', 'code', 'createdAt', 'defaultUom', 'id', 'isActive', 'name', 'tenantId', 'updatedAt'] as const
  $columns = OperationTypeSchema.$columns
  @column()
  declare category: string
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultUom: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OpportunitySchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'expectedCloseDate', 'expectedValue', 'id', 'stage', 'tenantId', 'title', 'updatedAt'] as const
  $columns = OpportunitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column.date()
  declare expectedCloseDate: DateTime | null
  @column()
  declare expectedValue: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare stage: string
  @column()
  declare tenantId: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PackagingUnitSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'isActive', 'name', 'tenantId', 'unitQuantity', 'uom', 'updatedAt'] as const
  $columns = PackagingUnitSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare tenantId: number
  @column()
  declare unitQuantity: string | null
  @column()
  declare uom: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PackingEntrySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'locationId', 'packageCount', 'packagingUnitId', 'packedAt', 'productionBatchId', 'quantity', 'status', 'stockLotId', 'tenantId', 'updatedAt'] as const
  $columns = PackingEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare locationId: number
  @column()
  declare packageCount: string
  @column()
  declare packagingUnitId: number
  @column.dateTime()
  declare packedAt: DateTime | null
  @column()
  declare productionBatchId: number | null
  @column()
  declare quantity: string
  @column()
  declare status: string
  @column()
  declare stockLotId: number | null
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'method', 'paidAt', 'saleId', 'status', 'tenantId', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare method: string
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare saleId: number
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PieceRateRuleSchema extends BaseModel {
  static $columns = ['createdAt', 'endsAt', 'id', 'isActive', 'itemId', 'operationTypeId', 'rate', 'startsAt', 'tenantId', 'uom', 'updatedAt', 'workerRoleId', 'workstationId'] as const
  $columns = PieceRateRuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endsAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare itemId: number | null
  @column()
  declare operationTypeId: number | null
  @column()
  declare rate: string
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare tenantId: number
  @column()
  declare uom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workerRoleId: number | null
  @column()
  declare workstationId: number | null
}

export class ProductionBatchInputSchema extends BaseModel {
  static $columns = ['consumedQuantity', 'createdAt', 'id', 'itemId', 'plannedQuantity', 'productionBatchId', 'stockLotId', 'tenantId', 'uom', 'updatedAt'] as const
  $columns = ProductionBatchInputSchema.$columns
  @column()
  declare consumedQuantity: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare plannedQuantity: string
  @column()
  declare productionBatchId: number
  @column()
  declare stockLotId: number | null
  @column()
  declare tenantId: number
  @column()
  declare uom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductionBatchOutputSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'productionBatchId', 'quantity', 'stockLotId', 'tenantId', 'type', 'uom', 'updatedAt'] as const
  $columns = ProductionBatchOutputSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare productionBatchId: number
  @column()
  declare quantity: string
  @column()
  declare stockLotId: number | null
  @column()
  declare tenantId: number
  @column()
  declare type: string
  @column()
  declare uom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductionBatchSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'finishedAt', 'id', 'manufacturingOrderId', 'startedAt', 'status', 'tenantId', 'updatedAt'] as const
  $columns = ProductionBatchSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manufacturingOrderId: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PurchaseOrderLineSchema extends BaseModel {
  static $columns = ['createdAt', 'expectedDate', 'id', 'itemId', 'purchaseOrderId', 'quantity', 'receivedQuantity', 'tenantId', 'unitPrice', 'updatedAt'] as const
  $columns = PurchaseOrderLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare expectedDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare purchaseOrderId: number
  @column()
  declare quantity: string
  @column()
  declare receivedQuantity: string
  @column()
  declare tenantId: number
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PurchaseOrderSchema extends BaseModel {
  static $columns = ['createdAt', 'expectedAt', 'id', 'orderedAt', 'status', 'supplierId', 'supplierName', 'tenantId', 'updatedAt'] as const
  $columns = PurchaseOrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expectedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare orderedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare supplierId: number | null
  @column()
  declare supplierName: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PurchaseReceiptLineSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'purchaseOrderLineId', 'purchaseReceiptId', 'quantity', 'stockLotId', 'tenantId', 'unitCost', 'updatedAt'] as const
  $columns = PurchaseReceiptLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare purchaseOrderLineId: number | null
  @column()
  declare purchaseReceiptId: number
  @column()
  declare quantity: string
  @column()
  declare stockLotId: number
  @column()
  declare tenantId: number
  @column()
  declare unitCost: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PurchaseReceiptSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'locationId', 'purchaseOrderId', 'receivedAt', 'tenantId', 'updatedAt'] as const
  $columns = PurchaseReceiptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locationId: number
  @column()
  declare purchaseOrderId: number
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoutingOperationSchema extends BaseModel {
  static $columns = ['createdAt', 'cycleTime', 'id', 'inputUom', 'operationTypeId', 'outputUom', 'routingId', 'sequence', 'setupTime', 'tenantId', 'updatedAt', 'workstationId'] as const
  $columns = RoutingOperationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cycleTime: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inputUom: string | null
  @column()
  declare operationTypeId: number
  @column()
  declare outputUom: string | null
  @column()
  declare routingId: number
  @column()
  declare sequence: number
  @column()
  declare setupTime: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workstationId: number
}

export class RoutingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'itemId', 'name', 'tenantId', 'updatedAt'] as const
  $columns = RoutingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare itemId: number
  @column()
  declare name: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaleItemSchema extends BaseModel {
  static $columns = ['createdAt', 'discountTotal', 'id', 'itemId', 'quantity', 'saleId', 'stockLotId', 'tenantId', 'total', 'unitPrice', 'updatedAt'] as const
  $columns = SaleItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discountTotal: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare quantity: string
  @column()
  declare saleId: number
  @column()
  declare stockLotId: number | null
  @column()
  declare tenantId: number
  @column()
  declare total: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaleSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'discountTotal', 'id', 'locationId', 'soldAt', 'status', 'subtotal', 'tenantId', 'total', 'updatedAt'] as const
  $columns = SaleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number | null
  @column()
  declare discountTotal: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locationId: number
  @column.dateTime()
  declare soldAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare tenantId: number
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockLotSchema extends BaseModel {
  static $columns = ['createdAt', 'expiryDate', 'id', 'itemId', 'locationId', 'lotNumber', 'quantityAvailable', 'quantityInitial', 'status', 'tenantId', 'unitCost', 'updatedAt'] as const
  $columns = StockLotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare expiryDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare locationId: number
  @column()
  declare lotNumber: string
  @column()
  declare quantityAvailable: string
  @column()
  declare quantityInitial: string
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column()
  declare unitCost: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SupplierSchema extends BaseModel {
  static $columns = ['createdAt', 'document', 'email', 'id', 'name', 'phone', 'status', 'tenantId', 'updatedAt'] as const
  $columns = SupplierSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TenantUserSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'tenantId', 'updatedAt', 'userId'] as const
  $columns = TenantUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'parentId', 'slug', 'updatedAt'] as const
  $columns = TenantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare parentId: number | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkerProductionEntrySchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'itemId', 'occurredAt', 'operationEntryId', 'operationTypeId', 'quantity', 'rate', 'status', 'tenantId', 'uom', 'updatedAt', 'workerId', 'workerRoleId', 'workstationId'] as const
  $columns = WorkerProductionEntrySchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare operationEntryId: number | null
  @column()
  declare operationTypeId: number | null
  @column()
  declare quantity: string
  @column()
  declare rate: string
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column()
  declare uom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workerId: number
  @column()
  declare workerRoleId: number | null
  @column()
  declare workstationId: number | null
}

export class WorkerRoleAssignmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'tenantId', 'updatedAt', 'workerId', 'workerRoleId'] as const
  $columns = WorkerRoleAssignmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workerId: number
  @column()
  declare workerRoleId: number
}

export class WorkerRoleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'isActive', 'name', 'tenantId', 'updatedAt'] as const
  $columns = WorkerRoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkerSchema extends BaseModel {
  static $columns = ['createdAt', 'document', 'id', 'name', 'status', 'tenantId', 'updatedAt'] as const
  $columns = WorkerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkstationSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'hourlyRate', 'id', 'isActive', 'name', 'tenantId', 'type', 'updatedAt'] as const
  $columns = WorkstationSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hourlyRate: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare tenantId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
